### ISSUE TITLE
bug report: all comments become from Anonymous 

### ISSUE THREAD

**Issue by bestian** [pol-is/polisClientParticipation#1]
Hi, i've just created two polis discussion space. When users post their comments, system say that they're all form Anonymous.

I've check the "Require Auth to Comment" option box on configure page, but after that, the bug still happened. All comments after the configuration are still "form Anonymous".

links related:
[pol.is/89bzf78kbn](pol.is/89bzf78kbn)
[pol.is/4d43udhutj](pol.is/4d43udhutj)

**Comment by mbjorkegren** [comment]
Good catch, I'll look into this.

**Comment by mbjorkegren** [comment]
Ok, should be fixed now.

**Comment by bestian** [comment]
it works! thank you~

**Comment by bestian** [comment]
it works! thank you~
