### ISSUE TITLE
Opinion Groups in topic not showing any visualization even after enabling them

### ISSUE THREAD

**Issue by joel-zilliqa** [pol-is/polisClientParticipation#54]
Managed to get the entire polis infrastructure set up on via docker-compose and docker containers. Conversation topic creation seems fine, however, the visualization doesn't seem to be working. Specifically, the Opinion groups isn't displaying anything even after more than 9 participants have voted on the various comments.

![image](https://user-images.githubusercontent.com/56012934/73350505-1ddaea80-42c8-11ea-95f6-55b0d758f5bc.png)

**Comment by Annihilatopia** [comment]
It's not related to participation, but rather, missing environment variables in polisserver.
